apiVersion: v1
kind: ConfigMap
metadata:
  name: ecommerce-config
  labels:
    {{- include "ecommerce-chart.labels" . | nindent 4 }}
data:
  environment: {{ .Values.global.environment | quote }}
  # Aquí puedes agregar más configuraciones compartidas si es necesario
