# Image Tags Configuration for Microservices
# Update these values to deploy specific versions to your AKS cluster

services:
  api-gateway:
    image: ghcr.io/nicolas-cm/api-gateway
    tag: "0.1.0-dev.abc1234"  # Update this tag to deploy a different version
    
  user-service:
    image: ghcr.io/nicolas-cm/user-service
    tag: "0.1.0-dev.abc1234"
    
  product-service:
    image: ghcr.io/nicolas-cm/product-service
    tag: "0.1.0-dev.abc1234"
    
  order-service:
    image: ghcr.io/nicolas-cm/order-service
    tag: "0.1.0-dev.abc1234"
    
  payment-service:
    image: ghcr.io/nicolas-cm/payment-service
    tag: "0.1.0-dev.abc1234"
    
  shipping-service:
    image: ghcr.io/nicolas-cm/shipping-service
    tag: "0.1.0-dev.abc1234"
    
  favourite-service:
    image: ghcr.io/nicolas-cm/favourite-service
    tag: "0.1.0-dev.abc1234"
    
  cloud-config:
    image: ghcr.io/nicolas-cm/cloud-config
    tag: "0.1.0-dev.abc1234"
    
  service-discovery:
    image: ghcr.io/nicolas-cm/service-discovery
    tag: "0.1.0-dev.abc1234"

# How to use:
# 1. Check available tags: gh api /user/packages/container/api-gateway/versions
# 2. Update the tag you want to use for each service
# 3. Run: helm upgrade --install microservices ./k8s/helm/microservices -f k8s/helm/image-tags.yaml
