# Values override for STAGE environment
imageTags:
  cloud-config: "0.1.0"
  service-discovery: "0.1.0"
  api-gateway: "0.1.0"
  product-service: "0.1.0"
  order-service: "0.1.0"
  user-service: "0.1.0"
  payment-service: "0.1.0"
  shipping-service: "0.1.0"
  favourite-service: "0.1.0"
  proxy-client: "0.1.0"
