# Values override for PRODUCTION environment
imageTags:
  cloud-config: "0.1.0-prod-multi"
  service-discovery: "0.1.0-prod-multi"
  api-gateway: "0.1.0-prod-multi"
  product-service: "0.1.0-prod-multi"
  order-service: "0.1.0-prod-multi"
  user-service: "0.1.0-prod-multi"
  payment-service: "0.1.0-prod-multi"
  shipping-service: "0.1.0-prod-multi"
  favourite-service: "0.1.0-prod-multi"
  proxy-client: "0.1.0-prod-multi"