# Values override for STAGE environment
imageTags:
  cloud-config: "0.1.0-stage.e69bbe8"
  service-discovery: "0.1.0-stage.e69bbe8"
  api-gateway: "0.1.0-stage.e69bbe8"
  product-service: "0.1.0-stage.e69bbe8"
  order-service: "0.1.0-stage.e69bbe8"
  user-service: "0.1.0-stage.e69bbe8"
  payment-service: "0.1.0-stage.e69bbe8"
  shipping-service: "0.1.0-stage.e69bbe8"
  favourite-service: "0.1.0-stage.e69bbe8"
  proxy-client: "0.1.0-stage.e69bbe8"
