# Values override for PRODUCTION environment
imageTags:
  cloud-config: "0.2.0"
  service-discovery: "0.2.0"
  api-gateway: "0.0.1"
  product-service: "0.2.0"
  order-service: "0.2.0"
  user-service: "0.2.0"
  payment-service: "0.2.0"
  shipping-service: "0.2.0"
  favourite-service: "0.2.0"
  proxy-client: "0.0.1"
