# Values override for PRODUCTION environment
imageTags:
  cloud-config: "1.0.0"
  service-discovery: "1.0.0"
  api-gateway: "1.0.0"
  product-service: "1.0.0"
  order-service: "1.0.0"
  user-service: "1.0.0"
  payment-service: "1.0.0"
  shipping-service: "1.0.0"
  favourite-service: "1.0.0"
  proxy-client: "1.0.0"
